Nope, this won't work.
After a long battle against .NET and Unity, I found out that it never had
an actual chance of working, because apparently Unity's Mono distribution
does not supply some essential .NET classes.

DllNotFoundException: .../libMonoPosixHelper.so
System.IO.Compression.DeflateStreamNative.Create

This exception occurs during an attempt to execute a Sheets API request.
Seems to behave the same on both desktop/Editor and Android.